production:
  captcha_key: <%= ENV['CAPTCHA_KEY'] %>
  contact_email_recipients: <%= ENV['CONTACT_EMAIL_RECIPIENTS'] %>
  postgres:
     adapter: postgres
     database: <%= ENV['RDS_DB_NAME'] %>
     username: <%= ENV['RDS_USERNAME'] %>
     password: <%= ENV['RDS_PASSWORD'] %>
     host: <%= ENV['RDS_HOSTNAME'] %>
     port: <%= ENV['RDS_PORT'] %>

development:
  captcha_key: <%= ENV['CAPTCHA_KEY'] %>
  contact_email_recipients: <%= ENV['CONTACT_EMAIL_RECIPIENTS'] %>
  postgres:
    adapter: <%= ENV['POSTGRES_DB_ADAPTER'] || 'postgres' %>
    database: <%= ENV['POSTGRES_DB_DATABASE'] || 'mastateat' %>
    username: <%= ENV['POSTGRES_DB_USERNAME'] || 'mastateat' %>
    password: <%= ENV['POSTGRES_DB_PASSWORD'] || 'mastateat' %>
    host: <%= ENV['POSTGRES_DB_HOST'] || 'localhost' %>
    port: <%= ENV['POSTGRES_DB_PORT'] || '10000' %>
  pretend_admin: true

test:
  captcha_key: <%= ENV['CAPTCHA_KEY'] %>
  contact_email_recipients: <%= ENV['CONTACT_EMAIL_RECIPIENTS'] %>
  postgres:
    adapter: <%= ENV['POSTGRES_DB_ADAPTER'] || 'postgres' %>
    database: <%= ENV['POSTGRES_DB_DATABASE'] || 'mastateat' %>
    username: <%= ENV['POSTGRES_DB_USERNAME'] || 'mastateat' %>
    password: <%= ENV['POSTGRES_DB_PASSWORD'] || 'mastateat' %>
    host: <%= ENV['POSTGRES_DB_HOST'] || 'localhost' %>
    port: <%= ENV['POSTGRES_DB_PORT'] || '10000' %>
  pretend_admin: false
